# Generated by Django 5.2.5 on 2025-08-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_user_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField(max_length=10)),
                ('product_des', models.CharField(max_length=200)),
                ('customer_id', models.CharField(max_length=200)),
            ],
        ),
    ]
