# Generated by Django 5.2.5 on 2025-08-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='product_img',
        ),
    ]
