# Generated by Django 5.2.5 on 2025-08-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_photo_product_product_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
