# Generated by Django 5.2.5 on 2025-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_customer_password_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(default='Order Placed', max_length=100),
        ),
    ]
