# Generated by Django 5.2.5 on 2025-08-26 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer'),
        ),
    ]
